# Generated by Django 5.1.4 on 2025-01-04 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='آدرس')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('producer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
        ),
    ]
