# Generated by Django 5.1.4 on 2025-01-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, verbose_name='قیمت'),
        ),
    ]
