# Generated by Django 5.1.4 on 2025-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام فرستنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل فرستنده')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساحته شده در')),
            ],
        ),
    ]
