# Generated by Django 5.1.4 on 2025-01-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام  دریافتی', 'verbose_name_plural': 'پیام های دریافتی'},
        ),
    ]
